### ISSUE TITLE
Organisation du repo

### ISSUE THREAD

**Issue by Rollybre** [Piraxe/HN-2023-Nevers#10]
Je suis entrain de créer sur ma branche une structure type pour le repo. Dites moi ce que vous en pensez.

**Comment by Emiliegd14** [comment]
Je trouve que ta structure est pertinente. Néanmoins, j'émets un questionnement : dans le dossier [GitHub - HN-2023-Nevers - Alexandre/transcriptions_individuelles](https://github.com/Piraxe/HN-2023-Nevers/tree/Alexandre/transcriptions_individuelles), pensez-vous qu'il faille mieux mettre nos transcriptions par dossier nominatif ou bien étant donné que nous avons travaillé sur un ensemble de folios qui se suivaient, mettre tout simplement dans le dossier général tous nos folios à la suite?

**Comment by Rollybre** [comment]
On peut peut-être faire les deux : avoir un dossier avec nos transcriptions qui s'enchaînent (une sorte de document final en xml et / ou en txt) , et un dossier individuel où chacun met sa part de transcription. Ca facilitera peut être la correction des travaux individuels.

**Comment by Emiliegd14** [comment]
Je valide, good idea.

**Comment by Rollybre** [comment]
Je crée l'architecture de base sur la branche main puis on rebranch après ?

**Comment by Emiliegd14** [comment]
Si les autres sont d'accord, je pense que cela serait judicieux.
