### ISSUE TITLE
Répartition des pages à transcrire

### ISSUE THREAD

**Issue by ASchopenhauer** [Piraxe/HN-2023-Nevers#2]
Il serait bien de préciser dans le README le lien vers le manuscrit que nous utilisons, ainsi que le numéro des pages que chacun transcrit.
On peut déjà commencer par écrire en commentaire de cette issue nos numéros de pages.

**Comment by Rollybre** [comment]
J'ajoute le lien au readme !

**Comment by ASchopenhauer** [comment]
Pas sûre que d'écrire la répartition précise des pages dans la partie "Changelog" du README soit pertinente... J'ai créé une partie adéquate dans le README sous forme de tableau, incluant la future cross-validation des transcriptions. A voir si on supprime ou synthétise ce qui à été écrit sous Changelog, je n'y ai pas touché pour l'instant.
