### ISSUE TITLE
Normes de transcription

### ISSUE THREAD

**Issue by ASchopenhauer** [Piraxe/HN-2023-Nevers#3]
Comme nous l'avons dit lors de notre réunion précédente, Emilie Guidot sera en charge de créer le document concernant les normes de transcription. En effet, c'est elle qui a le plus de connaissances dans la matière. 

Vaudra-t-il mieux poser nos questions en commentaire de cette issue ou bien créer une autre issue par question ? Le document des normes de transcription sera sans doute amené à évoluer en fonction des difficultés rencontrées.

**Comment by Rollybre** [comment]
On peut passer par les commentaires si ça convient à tout le monde !

**Comment by Emiliegd14** [comment]
Je compte illustrer le fichier [normesTranscription.md](https://github.com/Piraxe/HN-2023-Nevers/blob/transcription-normes/normesTranscription.md). Pour cela, je vais prendre comme exemple des mots ou des signes qui apparaissent dans les folios du manuscrit que nous avons transcrit. A ce jour, il me manque trois exemples : 
1) le "et" tironien
2) le point médian
3) les chiffres (en chiffre romain)

Si jamais vous pouvez me faire parvenir ces exemples, je vous remercie !

**Comment by Emiliegd14** [comment]
Autre question : dans le manuscrit, nous repérons deux manières de former le "s": le « s » (s rond) et « ſ » (s long). Etant donné que nous nous plaçons dans une optique de transcription graphématique, il serait logique de les transcrire tous deux en "s". Qu'en pensez-vous?

**Comment by Rollybre** [comment]
Dans l'optique de produire une vérité terrain pour le modèle, il me semble cohérent de transcrire avec un s rond, vu que le modèle transcrit avec un s rond lui aussi.
