### ISSUE TITLE
Clavier virtuel

### ISSUE THREAD

**Issue by ASchopenhauer** [Piraxe/HN-2023-Nevers#4]
Comme nous l'avons décidé lors de notre dernière réunion, je m'occuperai de créer le clavier virtuel. 

Merci de mettre en commentaire des photos de bouts de manuscrits pour lesquels vous pourriez avoir besoin de caractères dont vous ne disposez pas dans votre clavier de base. Nous nous appuierons également sur les normes de transcriptions fournies par Emilie Guidot.

**Comment by ASchopenhauer** [comment]
Je vais ouvrir d'autres issues concernant des questions que j'ai pour mes transcriptions... cela permettra d'étayer le document des normes et me permettra d'avancer sur le clavier.

**Comment by Piraxe** [comment]
![Caractère_special_PA_2](https://github.com/Piraxe/HN-2023-Nevers/assets/152303812/8bbf6865-576c-4810-b8c7-43634ec1a43e)
![Caractère_special_PA_3](https://github.com/Piraxe/HN-2023-Nevers/assets/152303812/66ad7dac-ea8f-4207-a331-9bdbd735b2d5)
![Caractère_special_PA_4](https://github.com/Piraxe/HN-2023-Nevers/assets/152303812/d7f952f0-61e7-41f5-a958-e506d7211b68)
![Caractère_special_PA_5](https://github.com/Piraxe/HN-2023-Nevers/assets/152303812/10e4e198-7609-4afa-8340-ba99e5e330e7)
![Caratère_spécial_PA_1](https://github.com/Piraxe/HN-2023-Nevers/assets/152303812/10ce6759-0f22-4eef-9b92-765c6be6bbad)

**Comment by Piraxe** [comment]
Et voici ! :)

**Comment by Emiliegd14** [comment]
@Piraxe 
1) C'est un "et" tironien. C'est l'une des touches que j'ai rajoutée avec ma pull request pour [lien_vers_clavier_virtuel_Cremmalab](https://github.com/Piraxe/HN-2023-Nevers/blob/main/Clavier/CremmaLab.json).
2)C'est l'abréviation du mot "plusieurs" avec un "r" et un "s" suscrit. Selon les normes de transcriptions, tu le transcriras de la sorte:  "pluse ͬ̾".
3) Abréviation du mot "chevaliers", mais tu l'avais trouvée tout seul. Tu transcriras par "chlrs̃".
4) Le p barré signifie "par" et l'abréviation qui suit "avant. A transcrire par "ꝑ auãt". 
5) Ici, on lit "notre Seigneur". A transcrire par : "nr̃e sͬ".
