### ISSUE TITLE
Problèmes de transcription

### ISSUE THREAD

**Issue by ASchopenhauer** [Piraxe/HN-2023-Nevers#6]
Issue grâce à laquelle nous pourrons poser nos questions concernant les difficultés rencontrées... Je commence donc !

## 1) A la fin de la première ligne, de quel signe s'agit-il ? D'un point ? Cela ressemble à ce signe "~".
![p16q1](https://github.com/Piraxe/HN-2023-Nevers/assets/153139719/ea45e5dd-e146-4354-9fb9-36baf0f427e7)

## 2) Comment transcrire les deux signes au-dessus du "q" ?
![p16q2](https://github.com/Piraxe/HN-2023-Nevers/assets/153139719/fc9186e3-49a5-49bf-b4e9-0e6e0b4c1269)

## 3) Faut-il en conclure qu'il y a deux manières d'écrire le "r" ?
![p16q3](https://github.com/Piraxe/HN-2023-Nevers/assets/153139719/2971dccb-46d3-470d-9cbd-89fa2bde5f8a)

## 4) Que faire de ceci en bas de mon document ?
![p16q4](https://github.com/Piraxe/HN-2023-Nevers/assets/153139719/2592a985-4a97-4ca6-8feb-a5a9581afea4)

## 5) S'agit-il d'un "s" ou d'un "d" ?
![p17q1](https://github.com/Piraxe/HN-2023-Nevers/assets/153139719/e1aaa88c-ecd1-4fe5-9198-a327e5b94a70)

**Comment by ASchopenhauer** [comment]
## 4) Que faire de ceci en bas de mon document ?
![p16q4](https://github.com/Piraxe/HN-2023-Nevers/assets/153139719/2592a985-4a97-4ca6-8feb-a5a9581afea4)

**Comment by Emiliegd14** [comment]
Voici les réponses à tes questions @ASchopenhauer :

1) C'est un signe de renvoi : il indique que le mot "que" va de pair avec "avant" à la ligne suivante.  Ces deux mots ont une liaison marquée. Je vais réfléchir à la manière de le transcrire afin de bien le distinguer des tildes d'abréviations.

2) En m'appuyant sur les recommandations de l'article d'Ariane Pinche "Guide de transcription pour les manuscrits du Xe au XVe siècle" (URL :  https://hal.science/hal-03697382), présent dans le fichier [Sources_projet.md](https://github.com/Piraxe/HN-2023-Nevers/blob/main/Sources_projet.md), le signe que l'on emploiera pour signaler cette abréviation du mot "que" sera le tilde horizontal suscrit : « ̃».  L'autre signe concerne la ligne d'au-dessus : en se penchant plus précisément sur ce folio de manuscrit, on constate en effet que le signe est compris dans la réglure d'au-dessus. C'est un signe de ponctuation, plus précisément une virgule donc on le transcrira par ",".

3) Oui, voici deux graphies de la lettre "r" employées par le scribe.  Etant donné que nous avons choisi une transcription allographétique, on le transcrira tout simplement par "r".

4) Ce mot "isolé" est une reprise. En codicologie, la reprise dans un manuscrit désigne le fait de débuter une phrase sur la fin d'une page pour assurer la continuité du texte sur la page suivante en cas de perte de folios. Je propose de l'indiquer comme une zone mais de ne pas l'indiquer dans la transcription puisque de toute façon le mot est sur la page d'après. A voir dans la documentation Segmonto (URL :  https://segmonto.github.io/), si une zone est prévue à cette effet. Le cas échéant, je propose de créer une zone "CustomZone: reprise".

5) C'est une graphie du "d"  initial pour le mot "damoiselle".

**Comment by Rollybre** [comment]
<img width="43" alt="image" src="https://github.com/Piraxe/HN-2023-Nevers/assets/120097880/90c3e8f4-58f9-46fb-99e3-9a87e6e6692a">
Petit problème : je ne reconnais pas ce signe, transcrit par le modèle : "ꝰ"
Merci par avance !

**Comment by Rollybre** [comment]
<img width="596" alt="image" src="https://github.com/Piraxe/HN-2023-Nevers/assets/120097880/7ffb50bf-12d3-4de8-9e56-3adc6355ca43">
Avec plus de contexte

**Comment by Emiliegd14** [comment]
Une abréviation que je n'avais pas relevée ! Je vais la rajouter de ce pas dans le fichier [normesTranscription.md](https://github.com/Piraxe/HN-2023-Nevers/blob/transcription-normes/normesTranscription.md).
Ce signe qui ressemble à un "neuf" à l'envers et qui se trouve en fin de mot est l'abréviation de "us". Le mot ici est donc "vous".
