### ISSUE TITLE
Importation clavier

### ISSUE THREAD

**Issue by Rollybre** [Piraxe/HN-2023-Nevers#7]
Pour ceux qui en aurait besoin....

1. 
<img width="1129" alt="image" src="https://github.com/Piraxe/HN-2023-Nevers/assets/120097880/1ba60a9a-257b-468b-b7a1-c68bc77ea29e">

Cliquer sur le clavier en haut à gauche

2. 

Cliquer sur la zone de transcription : cela ouvre une fenêtre.

<img width="1129" alt="image" src="https://github.com/Piraxe/HN-2023-Nevers/assets/120097880/584e9744-04db-4c95-8d7e-225682e97aeb">

3. Dans cette fenêtre cliquer sur "manage keyboard"

4. Puis, cliquer sur "import keyboard" ! 
<img width="719" alt="image" src="https://github.com/Piraxe/HN-2023-Nevers/assets/120097880/9d2ba669-f3be-402e-a82e-9c3437204d04">

**Comment by Emiliegd14** [comment]
Parfait, merci @Rollybre. Je vais créer un tableau avec les signes dont nous avons besoin et voir si tout est bon dans le clavier importé.

**Comment by Piraxe** [comment]
Merci 😩
