### ISSUE TITLE
Problème avec le fichier Sources_projet

### ISSUE THREAD

**Issue by Emiliegd14** [Piraxe/HN-2023-Nevers#8]
En effectuant l'action push sur le fichier [Sources_projet.md](https://github.com/Piraxe/HN-2023-Nevers/blob/main/Sources_projet.md), j'ai commis une erreur en le mettant directement sur la branche main. Je l'ai transféré dans une branche nommée bibliographie mais il apparaît toujours sur la branche main. Pensez-vous que je peux supprimer le fichier de la branche main sans impact?

**Comment by Rollybre** [comment]
Normalement ça ne devrait pas poser de problème. Vu qu'on a tous fait des branches, la version existe encore au cas où.
