### ISSUE TITLE
Question de titres pour les zones sur E-scriptorium

### ISSUE THREAD

**Issue by Emiliegd14** [Piraxe/HN-2023-Nevers#9]
Une question de dernière minute qui m'interpelle : en relisant vos folios, notamment le folio 4 de @Piraxe  et le folio 16 de @ASchopenhauer (tu avais déjà évoqué cette question dans l'issue sur les problèmes de transcription par ailleurs), je me demandais si nous créons une région spéciale dans l'ontologie d'E-Scriptorium pour le "mais" de reprise au folio 16. Je ne vois pas sur la documentation Segmonto une région dédiée particulièrement à cela. 

![Reprisef16](https://github.com/Piraxe/HN-2023-Nevers/assets/153830067/2ec3946b-45d5-4501-bd44-7ef4c7901a11)

En ce qui concerne le folio 4,  le texte isolé en rouge en bas de folio n'est pas une reprise en soi. Le texte est mis en valeur avec une couleur différente et ce genre de procédé indique généralement un changement important dans la structuration textuelle : début/fin de paragraphe, annonce du prologue/épilogue. Ici il est clair que nous avons affaire à l'annonce de la fin du prologue. Pensez-vous qu'il est judicieux de dédier à ce texte une région spéciale?

![Passagemarquéf4](https://github.com/Piraxe/HN-2023-Nevers/assets/153830067/9960e8d8-e337-4e70-8797-0fb2d288fd84)

**Comment by Piraxe** [comment]
Très bonne question ! Sais-tu s'il y a un moyen de créer de nouveaux types de zones sur eScriptorium ?

**Comment by Piraxe** [comment]
Je vais aller voir ça

**Comment by Piraxe** [comment]
Non mais nous avons à disposition 6 types de zones différentes, on peut peut-être décider que le texte principal soit du main, et les zones qui diffèrent du text ou du commentaire ? Je sais pas ce que t'en penses, faut-il vraiment faire la différence  ?

**Comment by Piraxe** [comment]
Ah j'ai rien dit ! On peut créer des zones sur l'onglet Ontology  ! C'était marqué dans la documentation segmonto : https://segmonto.github.io/gd/gdZ/CustomZone/
